# Generated by Django 4.2.1 on 2023-06-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0018_playlist_music_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('pop music', 'pop music'), ('Rock', 'Rock'), ('Phonk', 'Phonk'), ('House', 'House'), ('Electronic pop music', 'Electronic pop music'), ('Indi', 'Indi'), ('Electro', 'Electro'), ('Alternative Rock', 'Alternative Rock'), ('Dicko', 'Dicko')], default='Album', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.CharField(choices=[('Album', 'Album'), ('Bollywood', 'Bollywood'), ('Hollywood', 'Hollywood')], default='Classical', max_length=20),
        ),
    ]
