# Generated by Django 4.1.4 on 2023-06-09 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_app', '0019_alter_song_genre_alter_song_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История'},
        ),
        migrations.AlterModelOptions(
            name='likedsong',
            options={'verbose_name': 'Понравившиеся песни'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Плейлист', 'verbose_name_plural': 'Плейлисты'},
        ),
        migrations.AlterModelOptions(
            name='singer',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='likedsong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='followers',
            field=models.IntegerField(default=0, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_name',
            field=models.CharField(default='', max_length=10000000, verbose_name='Название плейлиста'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='plays',
            field=models.IntegerField(default=0, verbose_name='Воспроизвести'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='image',
            field=models.ImageField(upload_to='images/Singer', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='song',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Номер песни'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('pop music', 'Поп музыка'), ('Rock', 'Рок'), ('Phonk', 'Фонк'), ('House', 'Хаус'), ('Electronic pop music', 'Электро-поп'), ('Indi', 'Инди'), ('Electro', 'Электро'), ('Alternative Rock', 'Альтернативный рок'), ('Dicko', 'Диско')], default='Album', max_length=20, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Хинди'), ('Engligh', 'Английский'), ('Russian', 'Русский'), ('Tartarian', 'Татарский'), ('French', 'Французский')], default='Hindi', max_length=20, verbose_name='Язык исполнения'),
        ),
        migrations.AlterField(
            model_name='song',
            name='movie',
            field=models.CharField(default='', max_length=500, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='song',
            name='productionHouse',
            field=models.CharField(choices=[('T-Series', 'T-Series'), ('Sony Music', 'Sony Music'), ('Unknown', 'Неизвестный')], default='Unknown', max_length=20, verbose_name='Продюсерский дом'),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer1',
            field=models.CharField(max_length=200, verbose_name='Первый исполнитель'),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer2',
            field=models.CharField(default='', max_length=200, verbose_name='Второй исполнитель'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to='songs', verbose_name='Песня'),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.CharField(choices=[('Album', 'Альбом'), ('Bollywood', 'Болливуд'), ('Hollywood', 'Голливуд')], default='Classical', max_length=20, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1995', '1995'), ('1990', '1990'), ('1985', '1985')], default='2021', max_length=20, verbose_name='Год выпуска'),
        ),
    ]
